name: ez_validator
description: Dead simple field/object schema validation for flutter,EzValidator api is inspired by Yup
version: 0.3.1
homepage: https://github.com/X-SLAYER/EzValidator
documentation: https://github.com/X-SLAYER/EzValidator#methods

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.16.8
  lints: ^3.0.0
